### ISSUE TITLE
Road to 2.0.0

### ISSUE THREAD

**Issue by fschade** [owncloud/cdperf#51]
## Abstract
this issue wraps the open and needed steps on the road to 2.0.0.
The roadmap could extend over time, no concrete release date so far.

## Roadmap:
* 2.0.0-rc.1
  * [X] make client use modern apis for ocis
  * [X] add surf test
  * [X] add oc share-upload-rename test
  * [X] rely on k6 only, get rid of cdperf bash script
* 2.0.0-rc.2
  * [X] convert to mono repo
  * [X] add repo helper packages to build, lint, watch and setup tsconfig for the project more easy
  * [X] add test development toolkit package which abstracts away the client, utils and enpoints
  * [X] create dedicated tests package and ship the artifacts as part of it.
  * [X] add koko login test and depending apis
  * [X] add koko file tree navigation test and depending apis
  * [X] add koko upload delete test and depending apis
  * [X] add koko upload download test and depending apis
  * [X] add koko create and rename folder test and depending apis
  * [X] add showcase test to demonstrate tdk capabilities
  * [X] create readme for each test to provide information what the test does and how to use it
* 2.0.0-rc.3
  * [ ] add koko user group search and share test and depending apis
   review needed: https://github.com/owncloud/cdperf/pull/47
  * [ ] add koko create space test and depending apis
  review needed: https://github.com/owncloud/cdperf/pull/48
  * [ ] add koko add remove user share test and depending apis
  review needed: https://github.com/owncloud/cdperf/pull/49
  * [ ] add koko search for filename test and depending apis
  review needed: https://github.com/owncloud/cdperf/pull/50
* 2.0.0-rc.4
  * [ ] cleanup tdk endpoints, the api's for oCis, occ and nc are more clear now
  * [ ] cleanup tdk client, the api's for oCis, occ and nc are more clear now
  * [ ] introduce snipped's or workflow package (abstract away complex tasks like tag find or create, ...)
  * [ ] review and cleanup written tests
* 2.0.0-rc.5
  * [ ] refactor auth adapters and add keycloak compatible adapter
  https://github.com/owncloud/cdperf/issues/42
  * [ ] find solution to not relay on polling to find out if a resource is ready to use or not (ocis search indexing, ocis async uploads)
* 2.0.0-rc.6
  * [ ] add custom xk6 package to be able to share big binary data between vu's, similar like k6 sharedArray but for bin data
  * [ ] use TUS for ocis file uploads
  https://github.com/owncloud/cdperf/issues/43
  * ...

## Appendix
not sure what else is needed since the testing starts in the near future and we have to see whats missing or not... roadmap could extend depending on the results.

**Comment by fschade** [comment]
We could, but i see no relation between ocis and cdperf… i don’t care mich about Version numbers as Long as we follow semver style
